//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myownFYPAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeType
    {
        public EmployeeType()
        {
            this.EmployeSessionKPI = new HashSet<EmployeSessionKPI>();
            this.KPI = new HashSet<KPI>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<EmployeSessionKPI> EmployeSessionKPI { get; set; }
        public virtual ICollection<KPI> KPI { get; set; }
    }
}
