//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myownFYPAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fypapiv1Entities : DbContext
    {
        public fypapiv1Entities()
            : base("name=fypapiv1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Course> Course { get; set; }
        public DbSet<CourseAllocation> CourseAllocation { get; set; }
        public DbSet<EmployeeType> EmployeeType { get; set; }
        public DbSet<EmployeSessionKPI> EmployeSessionKPI { get; set; }
        public DbSet<Enrollment> Enrollment { get; set; }
        public DbSet<KPI> KPI { get; set; }
        public DbSet<KPIScore> KPIScore { get; set; }
        public DbSet<PeerEvaluation> PeerEvaluation { get; set; }
        public DbSet<PeerEvaluator> PeerEvaluator { get; set; }
        public DbSet<Questionare> Questionare { get; set; }
        public DbSet<Session> Session { get; set; }
        public DbSet<Student> Student { get; set; }
        public DbSet<StudentEvaluation> StudentEvaluation { get; set; }
        public DbSet<SubKPI> SubKPI { get; set; }
        public DbSet<Teacher> Teacher { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Questions> Questions { get; set; }
    }
}
