//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myownFYPAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeerEvaluator
    {
        public PeerEvaluator()
        {
            this.PeerEvaluation = new HashSet<PeerEvaluation>();
        }
    
        public int id { get; set; }
        public string teacherID { get; set; }
        public Nullable<int> sessionID { get; set; }
    
        public virtual ICollection<PeerEvaluation> PeerEvaluation { get; set; }
        public virtual Session Session { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
