//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myownFYPAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.StudentEvaluation = new HashSet<StudentEvaluation>();
            this.PeerEvaluation = new HashSet<PeerEvaluation>();
        }
    
        public int QuestionID { get; set; }
        public int QuestionareID { get; set; }
        public string QuestionText { get; set; }
    
        public virtual Questionare Questionare { get; set; }
        public virtual ICollection<StudentEvaluation> StudentEvaluation { get; set; }
        public virtual ICollection<PeerEvaluation> PeerEvaluation { get; set; }
    }
}
