//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myownFYPAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionare
    {
        public Questionare()
        {
            this.PeerEvaluation = new HashSet<PeerEvaluation>();
            this.StudentEvaluation = new HashSet<StudentEvaluation>();
            this.Questions = new HashSet<Questions>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
        public string flag { get; set; }
    
        public virtual ICollection<PeerEvaluation> PeerEvaluation { get; set; }
        public virtual ICollection<StudentEvaluation> StudentEvaluation { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
