//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myownFYPAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Societies
    {
        public Societies()
        {
            this.SocietyAssignments = new HashSet<SocietyAssignments>();
            this.SocietyEvaluation = new HashSet<SocietyEvaluation>();
        }
    
        public int SocietyId { get; set; }
        public string SocietyName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SocietyAssignments> SocietyAssignments { get; set; }
        public virtual ICollection<SocietyEvaluation> SocietyEvaluation { get; set; }
    }
}
