//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myownFYPAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Enrollment = new HashSet<Enrollment>();
        }
    
        public string userID { get; set; }
        public string name { get; set; }
        public Nullable<int> admissionSessionID { get; set; }
    
        public virtual ICollection<Enrollment> Enrollment { get; set; }
        public virtual Session Session { get; set; }
        public virtual Users Users { get; set; }
    }
}
