//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myownFYPAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubKPI
    {
        public SubKPI()
        {
            this.EmployeSessionKPI = new HashSet<EmployeSessionKPI>();
        }
    
        public int id { get; set; }
        public Nullable<int> KPIID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<EmployeSessionKPI> EmployeSessionKPI { get; set; }
        public virtual KPI KPI { get; set; }
    }
}
