//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myownFYPAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.CourseAllocation = new HashSet<CourseAllocation>();
            this.Enrollment = new HashSet<Enrollment>();
            this.PeerEvaluation = new HashSet<PeerEvaluation>();
            this.PeerEvaluator = new HashSet<PeerEvaluator>();
        }
    
        public string userID { get; set; }
        public string name { get; set; }
        public string department { get; set; }
    
        public virtual ICollection<CourseAllocation> CourseAllocation { get; set; }
        public virtual ICollection<Enrollment> Enrollment { get; set; }
        public virtual ICollection<PeerEvaluation> PeerEvaluation { get; set; }
        public virtual ICollection<PeerEvaluator> PeerEvaluator { get; set; }
        public virtual Users Users { get; set; }
    }
}
